spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdbb;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    import:
      - classpath:/aws.yml

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

